// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package com.smartcity.airquality;

public final class Airquality {
  private Airquality() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcity_airquality_AirQualityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcity_airquality_AirQualityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcity_airquality_PollutionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcity_airquality_PollutionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcity_airquality_AlertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcity_airquality_AlertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcity_airquality_AlertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcity_airquality_AlertResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020airquality.proto\022\024smartcity.airquality" +
      "\"%\n\021AirQualityRequest\022\020\n\010location\030\001 \001(\t\"" +
      ">\n\021PollutionResponse\022\020\n\010location\030\001 \001(\t\022\027" +
      "\n\017pollution_level\030\002 \001(\002\"7\n\014AlertRequest\022" +
      "\020\n\010location\030\001 \001(\t\022\025\n\ralert_message\030\002 \001(\t" +
      "\"%\n\rAlertResponse\022\024\n\014confirmation\030\001 \001(\t2" +
      "\333\001\n\021AirQualityService\022g\n\021MonitorAirQuali" +
      "ty\022\'.smartcity.airquality.AirQualityRequ" +
      "est\032\'.smartcity.airquality.PollutionResp" +
      "onse0\001\022]\n\020AlertAuthorities\022\".smartcity.a" +
      "irquality.AlertRequest\032#.smartcity.airqu" +
      "ality.AlertResponse(\001B\034\n\030com.smartcity.a" +
      "irqualityP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartcity_airquality_AirQualityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartcity_airquality_AirQualityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcity_airquality_AirQualityRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_smartcity_airquality_PollutionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartcity_airquality_PollutionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcity_airquality_PollutionResponse_descriptor,
        new java.lang.String[] { "Location", "PollutionLevel", });
    internal_static_smartcity_airquality_AlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartcity_airquality_AlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcity_airquality_AlertRequest_descriptor,
        new java.lang.String[] { "Location", "AlertMessage", });
    internal_static_smartcity_airquality_AlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartcity_airquality_AlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcity_airquality_AlertResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
