// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package com.smartcity.airquality;

public interface AlertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcity.airquality.AlertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation = 1;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
