// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package com.smartcity.airquality;

public interface AlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcity.airquality.AlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string alert_message = 2;</code>
   */
  java.lang.String getAlertMessage();
  /**
   * <code>string alert_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getAlertMessageBytes();
}
