// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package com.smartcity.airquality;

public interface PollutionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcity.airquality.PollutionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>float pollution_level = 2;</code>
   */
  float getPollutionLevel();
}
