// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parking.proto

package com.smartcity.parking;

public interface ParkingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcity.parking.ParkingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string available_spots = 1;</code>
   */
  java.util.List<java.lang.String>
      getAvailableSpotsList();
  /**
   * <code>repeated string available_spots = 1;</code>
   */
  int getAvailableSpotsCount();
  /**
   * <code>repeated string available_spots = 1;</code>
   */
  java.lang.String getAvailableSpots(int index);
  /**
   * <code>repeated string available_spots = 1;</code>
   */
  com.google.protobuf.ByteString
      getAvailableSpotsBytes(int index);
}
