// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parking.proto

package com.smartcity.parking;

public final class Parking {
  private Parking() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcity_parking_ParkingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcity_parking_ParkingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcity_parking_ParkingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcity_parking_ParkingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcity_parking_ReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcity_parking_ReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcity_parking_ReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcity_parking_ReservationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rparking.proto\022\021smartcity.parking\"\"\n\016Pa" +
      "rkingRequest\022\020\n\010location\030\001 \001(\t\"*\n\017Parkin" +
      "gResponse\022\027\n\017available_spots\030\001 \003(\t\">\n\022Re" +
      "servationRequest\022\017\n\007user_id\030\001 \001(\t\022\027\n\017par" +
      "king_spot_id\030\002 \001(\t\"3\n\023ReservationRespons" +
      "e\022\034\n\024confirmation_message\030\001 \001(\t2\326\001\n\016Park" +
      "ingService\022]\n\024FindAvailableParking\022!.sma" +
      "rtcity.parking.ParkingRequest\032\".smartcit" +
      "y.parking.ParkingResponse\022e\n\022ReservePark" +
      "ingSpot\022%.smartcity.parking.ReservationR" +
      "equest\032&.smartcity.parking.ReservationRe" +
      "sponse(\001B\031\n\025com.smartcity.parkingP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartcity_parking_ParkingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartcity_parking_ParkingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcity_parking_ParkingRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_smartcity_parking_ParkingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartcity_parking_ParkingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcity_parking_ParkingResponse_descriptor,
        new java.lang.String[] { "AvailableSpots", });
    internal_static_smartcity_parking_ReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartcity_parking_ReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcity_parking_ReservationRequest_descriptor,
        new java.lang.String[] { "UserId", "ParkingSpotId", });
    internal_static_smartcity_parking_ReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartcity_parking_ReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcity_parking_ReservationResponse_descriptor,
        new java.lang.String[] { "ConfirmationMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
