// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parking.proto

package com.smartcity.parking;

public interface ParkingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcity.parking.ParkingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
