// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parking.proto

package com.smartcity.parking;

/**
 * Protobuf type {@code smartcity.parking.ParkingResponse}
 */
public  final class ParkingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartcity.parking.ParkingResponse)
    ParkingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ParkingResponse.newBuilder() to construct.
  private ParkingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParkingResponse() {
    availableSpots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ParkingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              availableSpots_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            availableSpots_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        availableSpots_ = availableSpots_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartcity.parking.Parking.internal_static_smartcity_parking_ParkingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartcity.parking.Parking.internal_static_smartcity_parking_ParkingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartcity.parking.ParkingResponse.class, com.smartcity.parking.ParkingResponse.Builder.class);
  }

  public static final int AVAILABLE_SPOTS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList availableSpots_;
  /**
   * <code>repeated string available_spots = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getAvailableSpotsList() {
    return availableSpots_;
  }
  /**
   * <code>repeated string available_spots = 1;</code>
   */
  public int getAvailableSpotsCount() {
    return availableSpots_.size();
  }
  /**
   * <code>repeated string available_spots = 1;</code>
   */
  public java.lang.String getAvailableSpots(int index) {
    return availableSpots_.get(index);
  }
  /**
   * <code>repeated string available_spots = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAvailableSpotsBytes(int index) {
    return availableSpots_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < availableSpots_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, availableSpots_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < availableSpots_.size(); i++) {
        dataSize += computeStringSizeNoTag(availableSpots_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAvailableSpotsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartcity.parking.ParkingResponse)) {
      return super.equals(obj);
    }
    com.smartcity.parking.ParkingResponse other = (com.smartcity.parking.ParkingResponse) obj;

    boolean result = true;
    result = result && getAvailableSpotsList()
        .equals(other.getAvailableSpotsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAvailableSpotsCount() > 0) {
      hash = (37 * hash) + AVAILABLE_SPOTS_FIELD_NUMBER;
      hash = (53 * hash) + getAvailableSpotsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartcity.parking.ParkingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartcity.parking.ParkingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartcity.parking.ParkingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartcity.parking.ParkingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartcity.parking.ParkingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartcity.parking.ParkingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartcity.parking.ParkingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartcity.parking.ParkingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartcity.parking.ParkingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartcity.parking.ParkingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartcity.parking.ParkingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartcity.parking.ParkingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartcity.parking.ParkingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartcity.parking.ParkingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartcity.parking.ParkingResponse)
      com.smartcity.parking.ParkingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartcity.parking.Parking.internal_static_smartcity_parking_ParkingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartcity.parking.Parking.internal_static_smartcity_parking_ParkingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartcity.parking.ParkingResponse.class, com.smartcity.parking.ParkingResponse.Builder.class);
    }

    // Construct using com.smartcity.parking.ParkingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      availableSpots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartcity.parking.Parking.internal_static_smartcity_parking_ParkingResponse_descriptor;
    }

    @java.lang.Override
    public com.smartcity.parking.ParkingResponse getDefaultInstanceForType() {
      return com.smartcity.parking.ParkingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartcity.parking.ParkingResponse build() {
      com.smartcity.parking.ParkingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartcity.parking.ParkingResponse buildPartial() {
      com.smartcity.parking.ParkingResponse result = new com.smartcity.parking.ParkingResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        availableSpots_ = availableSpots_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.availableSpots_ = availableSpots_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartcity.parking.ParkingResponse) {
        return mergeFrom((com.smartcity.parking.ParkingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartcity.parking.ParkingResponse other) {
      if (other == com.smartcity.parking.ParkingResponse.getDefaultInstance()) return this;
      if (!other.availableSpots_.isEmpty()) {
        if (availableSpots_.isEmpty()) {
          availableSpots_ = other.availableSpots_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAvailableSpotsIsMutable();
          availableSpots_.addAll(other.availableSpots_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartcity.parking.ParkingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartcity.parking.ParkingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList availableSpots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAvailableSpotsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        availableSpots_ = new com.google.protobuf.LazyStringArrayList(availableSpots_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string available_spots = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAvailableSpotsList() {
      return availableSpots_.getUnmodifiableView();
    }
    /**
     * <code>repeated string available_spots = 1;</code>
     */
    public int getAvailableSpotsCount() {
      return availableSpots_.size();
    }
    /**
     * <code>repeated string available_spots = 1;</code>
     */
    public java.lang.String getAvailableSpots(int index) {
      return availableSpots_.get(index);
    }
    /**
     * <code>repeated string available_spots = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAvailableSpotsBytes(int index) {
      return availableSpots_.getByteString(index);
    }
    /**
     * <code>repeated string available_spots = 1;</code>
     */
    public Builder setAvailableSpots(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAvailableSpotsIsMutable();
      availableSpots_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string available_spots = 1;</code>
     */
    public Builder addAvailableSpots(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAvailableSpotsIsMutable();
      availableSpots_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string available_spots = 1;</code>
     */
    public Builder addAllAvailableSpots(
        java.lang.Iterable<java.lang.String> values) {
      ensureAvailableSpotsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, availableSpots_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string available_spots = 1;</code>
     */
    public Builder clearAvailableSpots() {
      availableSpots_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string available_spots = 1;</code>
     */
    public Builder addAvailableSpotsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAvailableSpotsIsMutable();
      availableSpots_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartcity.parking.ParkingResponse)
  }

  // @@protoc_insertion_point(class_scope:smartcity.parking.ParkingResponse)
  private static final com.smartcity.parking.ParkingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartcity.parking.ParkingResponse();
  }

  public static com.smartcity.parking.ParkingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParkingResponse>
      PARSER = new com.google.protobuf.AbstractParser<ParkingResponse>() {
    @java.lang.Override
    public ParkingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ParkingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ParkingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParkingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartcity.parking.ParkingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

