// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parking.proto

package com.smartcity.parking;

public interface ReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcity.parking.ReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation_message = 1;</code>
   */
  java.lang.String getConfirmationMessage();
  /**
   * <code>string confirmation_message = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationMessageBytes();
}
