// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parking.proto

package com.smartcity.parking;

public interface ReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcity.parking.ReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string parking_spot_id = 2;</code>
   */
  java.lang.String getParkingSpotId();
  /**
   * <code>string parking_spot_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getParkingSpotIdBytes();
}
