// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emergency.proto

package com.smartcity.emergency;

public interface AccidentReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcity.emergency.AccidentReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string severity = 2;</code>
   */
  java.lang.String getSeverity();
  /**
   * <code>string severity = 2;</code>
   */
  com.google.protobuf.ByteString
      getSeverityBytes();
}
