// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emergency.proto

package com.smartcity.emergency;

public interface EmergencyUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcity.emergency.EmergencyUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string update_message = 1;</code>
   */
  java.lang.String getUpdateMessage();
  /**
   * <code>string update_message = 1;</code>
   */
  com.google.protobuf.ByteString
      getUpdateMessageBytes();
}
