// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emergency.proto

package com.smartcity.emergency;

public final class Emergency {
  private Emergency() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcity_emergency_AccidentReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcity_emergency_AccidentReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcity_emergency_EmergencyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcity_emergency_EmergencyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcity_emergency_EmergencyUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartcity_emergency_EmergencyUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017emergency.proto\022\023smartcity.emergency\"4" +
      "\n\016AccidentReport\022\020\n\010location\030\001 \001(\t\022\020\n\010se" +
      "verity\030\002 \001(\t\"#\n\020EmergencyRequest\022\017\n\007team" +
      "_id\030\001 \001(\t\")\n\017EmergencyUpdate\022\026\n\016update_m" +
      "essage\030\001 \001(\t2\332\001\n\020EmergencyService\022_\n\016Rep" +
      "ortAccident\022#.smartcity.emergency.Accide" +
      "ntReport\032$.smartcity.emergency.Emergency" +
      "Update(\0010\001\022e\n\024NotifyEmergencyTeams\022%.sma" +
      "rtcity.emergency.EmergencyRequest\032$.smar" +
      "tcity.emergency.EmergencyUpdate0\001B\033\n\027com" +
      ".smartcity.emergencyP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartcity_emergency_AccidentReport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartcity_emergency_AccidentReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcity_emergency_AccidentReport_descriptor,
        new java.lang.String[] { "Location", "Severity", });
    internal_static_smartcity_emergency_EmergencyRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartcity_emergency_EmergencyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcity_emergency_EmergencyRequest_descriptor,
        new java.lang.String[] { "TeamId", });
    internal_static_smartcity_emergency_EmergencyUpdate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartcity_emergency_EmergencyUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartcity_emergency_EmergencyUpdate_descriptor,
        new java.lang.String[] { "UpdateMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
