// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emergency.proto

package com.smartcity.emergency;

public interface EmergencyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcity.emergency.EmergencyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string team_id = 1;</code>
   */
  java.lang.String getTeamId();
  /**
   * <code>string team_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getTeamIdBytes();
}
